# Generated by Django 3.2 on 2023-03-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='debit',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='nip',
            field=models.CharField(max_length=16),
        ),
    ]
