# Generated by Django 3.2 on 2023-03-24 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0002_auto_20230324_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='withdraw',
            field=models.IntegerField(default=0),
        ),
    ]
