# Generated by Django 3.2 on 2023-03-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_accounts', '0003_bankaccount_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='nip_incorrect',
            field=models.IntegerField(default=0),
        ),
    ]
